<?php
use Vortexiq\Connect\Block\Adminhtml\System\Config\Button;

/** @var Button $block */
?>
<?= /** @noEscape */ $block->getButtonHtml() ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {

        var ajaxUrl = '<?= /** @noEscape */ $block->getData('xc_active_url') ?>',
            activeButton = jQuery('#vortexiq_module_active'),
            updateButton = jQuery('#vortexiq_module_update'),
            fieldKey = jQuery('.vortexiq-module-active-field-key'),
            freeFields = jQuery('.vortexiq-module-active-field-free'),
            emailField = jQuery('.vortexiq-module-active-email'),
            nameField = jQuery('.vortexiq-module-active-name'),
            messageContainer = jQuery('#vortexiq-module-messages'),
            saveButton = jQuery('#save');
            updateButton.hide();
        var submitData = {
                extension: '<?= /** @noEscape */ $block->getData('xc_module_name') ?>',
                domain: window.location.hostname
            };

        window.vortexiqModuleActive = function () {
            var errorMsg = {};
            if(emailField.val() != '' && validateEmail(emailField.val()) == false){
                errorMsg['message'] = 'Invalid Email address.';
                updateMessage(errorMsg);
                return false;
            }
            if(emailField.val() == '' || nameField.val() == ''){
                errorMsg['message'] = 'Please fill Customer Name and Email Id.';
                updateMessage(errorMsg);
                return false;
            }
            submitData.customer_email = emailField.val();
            submitData.name = nameField.val();
            messageContainer.hide();
            jQuery.ajax({
                url: ajaxUrl,
                data: submitData,
                dataType: 'json',
                showLoader: true,
                success: function (result) {
                    if (result.key) {
                        fieldKey.val(result.key);
                    }
                    updateMessage(result);
                    activateProduct(result.active);
                }
            });
        };

        window.vortexiqModuleUpdate = function () {
            submitData.update = 1;
            messageContainer.hide();
            updateButton.hide();
            activeButton.show();
            activeButton.find('span').html('Submit');
            activeButton.attr('title', 'Submit');

            fieldKey.closest('tr').hide();
            freeFields.closest('tr').show();
        };

        function activateProduct(active) {
            submitData.update = 0;
            if (active) {
                activeButton.hide();
                //updateButton.show();
                saveButton.attr('disabled', false);
                fieldKey.closest('tr').show();
                freeFields.closest('tr').hide();
            } else {
                saveButton.attr('disabled', 'disabled');
                updateButton.hide();
                activeButton.show();
                fieldKey.closest('tr').hide();
                freeFields.closest('tr').show();
            }
        }

        function updateMessage(result) {
            if (result.message) {
                messageContainer.show();
                messageContainer.find('.message div').html(result.message);
                messageContainer.find('.message')
                    .removeClass('message-' + (result.success ? 'error' : 'success'))
                    .addClass('message-' + (result.success ? 'success' : 'error'));
            }
        }

        function validateEmail(email) {
            var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
              if(!regex.test(email)) {
                return false;
            }else{
                return true;
            }
        }

        var isActive = <?= /** @noEscape */ $block->getData('xc_is_active') ? 'true' : 'false' ?>;
        console.log('--isActive--',isActive);
        activateProduct(isActive);

        if (!isActive) {
            var containerId = '<?= /** @noEscape */ $block->getData('xc_module_html_id') ?>';
            $(containerId + '-state').value = 0;
            Fieldset.toggleCollapse(containerId);

            updateMessage({
                success: false,
                message: 'This extension is not activated.'
            });
        }

        fieldKey.attr('readonly', true);
        freeFields.removeAttr('name');
    });
</script>
